server:
  address: ${SERVER_ADDRESS}
  port: ${SERVER_PORT}

spring:
  application:
    name: obra-gestion

  servlet:
    multipart:
      max-file-size: ${FILE_SIZE}
      max-request-size: ${FILE_SIZE}
      file-size-threshold: ${FILE_SIZE_THRESHOLD}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
    hikari:
      maximum-pool-size: 500
      minimum-idle: 100
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DATABASE_PLATFORM}

  docker:
    compose:
      enabled: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

external-server:
  azure:
    storage:
      url: ${AZURE_STORAGE_URL}
    container:
      requerimiento: ${AZURE_CONTAINER_REQUERIMIENTO}
      construccion: ${AZURE_CONTAINER_CONSTRUCCION}
      comun: ${AZURE_CONTAINER_DOCUMENTOS}

logging:
  pattern:
    dateformat: hh:mm:ss